ip: 'localhost'
port: 8080
password: 'password'
secret-key: 'cfe285158af25f0baf9c31fd43c1b3d9369183c1df983a5b45f124cb35f86ae7'
current-server-id: 'auto_gen' # auto_gen - автоматически сгенерировать id если на сервере включён параметр `allow-anonymous-clients`